var data = {
  characters: [{
    name: 'Elena',
    voice: 'elena-e-paride.ogg',
    image: 'elena.png',
    x: 410,
    y: 684
  }, {
    name: 'Achille',
    voice: 'achille.ogg',
    image: 'achille.png',
    x: 200,
    y: 570
  }, {
    name: 'Isotta',
    voice: 'isotta.ogg',
    image: 'isotta.png',
    x: 1400,
    y: 390
  }, {
    name: 'Minosse',
    voice: 'minosse.ogg',
    image: 'minosse.png',
    x: 960,
    y: 200
  }, {
    name: 'Semiramide',
    voice: 'semiramide.ogg',
    image: 'semiramide.png',
    x: 1580,
    y: 420
  }, {
    name: 'Didone',
    voice: 'didone.ogg',
    image: 'didone.png',
    x: 720,
    y: 410
  }]
};