var data = {
  characters: [{
    name: 'Elena',
    voice: 'elena-e-paride.ogg',
    image: 'elena.png',
    x: 410,
    y: 684
  }, {
    name: 'Achille',
    voice: 'achille.ogg',
    image: 'achille.png',
    x: 200,
    y: 570
  }, {
    name: 'Isotta',
    voice: 'isotta.ogg',
    image: 'isotta.png',
    x: 1400,
    y: 390
  }, {
    name: 'Minosse',
    voice: 'minosse.ogg',
    image: 'minosse.png',
    x: 960,
    y: 200
  }, {
    name: 'Semiramide',
    voice: 'semiramide.ogg',
    image: 'semiramide.png',
    x: 1580,
    y: 420
  }, {
    name: 'Didone',
    voice: 'didone.ogg',
    image: 'didone.png',
    x: 720,
    y: 410
  }, {
    name: 'Cleopatra',
    voice: 'didone.ogg',
    image: 'cleopatra.png',
    x: 1700,
    y: 250
  }, {
    name: 'Francesca',
    voice: 'francesca.ogg',
    image: 'francesca.png',
    x: 1180,
    y: 650
  }, {
    name: 'Ginevra',
    voice: 'didone.ogg',
    image: 'ginevra.png',
    x: 370,
    y: 340
  }, {
    name: 'Lancilotto',
    voice: 'didone.ogg',
    image: 'lancilotto.png',
    x: 200,
    y: 290
  }, {
    name: 'Paolo',
    voice: 'didone.ogg',
    image: 'paolo.png',
    x: 1340,
    y: 640
  }, {
    name: 'Paride',
    voice: 'didone.ogg',
    image: 'paride.png',
    x: 680,
    y: 730
  }, {
    name: 'Tristano',
    voice: 'tristano.ogg',
    image: 'tristano.png',
    x: 1280,
    y: 370
  }]
};